feat: local-setup directly with prerelease component and traefik without istio
On-behalf-of: @SAP angel.kafazov@sap.com
Signed-off-by: Angel Kafazov <akafazov@cst-bg.net>

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -13,7 +13,7 @@ vars:
   GOARCH:
     sh: go env GOARCH
   OCM_VERSION: 0.29.0
-  COMPONENT_PRERELEASE_VERSION: "1.0.0"
+  COMPONENT_PRERELEASE_VERSION: "1.0.2"
   CUSTOM_LOCAL_COMPONENTS_CHART_PATHS:
     - account-operator: charts/account-operator
     - security-operator: charts/security-operator
@@ -158,7 +158,7 @@ tasks:
       - docker run -d --name proxy-k8s-io --restart=always --net=kind -e REGISTRY_PROXY_REMOTEURL=https://registry.k8s.io registry:2
 
   ocm:deploy:ociregistry:
-    internal: true
+    internal: false
     cmds:
       - |
         kind export kubeconfig -n platform-mesh
@@ -282,7 +282,7 @@ tasks:
       - task: ocm:transfer:dir-to-local-oci
 
   ocm:configure:tls:
-    internal: true
+    internal: false
     desc: Apply ocm-k8s-toolkit patch to support oci registry with self-signed certs
     cmds:
       - local-setup/scripts/configureOcmTls.sh
@@ -378,6 +378,8 @@ tasks:
         echo "--- finished getting component versions ---"
 
         set -x
+        kubectl exec -it ocm-transfer-pod -- ocm transfer componentversion ghcr.io/platform-mesh//github.com/platform-mesh/organization-idp:$ORGANIZATION_IDP_VERSION .ocm/transport.ctf
+
         kubectl exec -it ocm-transfer-pod -- ocm add components --lookup 'oci-registry-docker-registry.registry.svc.cluster.local' -c --templater=go --file ".ocm/transport.ctf" .ocm/component-constructor-prerelease.yaml -- \
         VERSION={{ .COMPONENT_PRERELEASE_VERSION }} \
         ISTIO_VERSION=$ISTIO_VERSION \
@@ -408,7 +410,7 @@ tasks:
       - task: ocm:transfer:dir-to-local-oci
 
   ocm:deploy:transfer-pod:
-    internal: true
+    internal: false
     cmds:
       - |
         set -e
@@ -431,52 +433,30 @@ tasks:
 
   ocm:deploy:
     cmds:
-      - task: ocm:deploy:ociregistry
-      - task: ocm:deploy:transfer-pod
-      - task: ocm:configure:tls
+      - |
+        set -e
+        kind export kubeconfig -n platform-mesh || true
 
-  ocm:kustomize:apply:
+        if kubectl get pod -n default ocm-transfer-pod >/dev/null 2>&1; then
+          echo "ocm-transfer-pod already exists, skipping deploy."
+          exit 0
+        fi
+
+        task ocm:deploy:ociregistry
+        task ocm:deploy:transfer-pod
+        task ocm:configure:tls
+
+  ocm:apply:
     aliases:
-      - ocm:apply
+      - ocm:kustomize:apply
     cmds:
       - kind export kubeconfig -n platform-mesh
       - |
         echo "Applying kustomize overlay to deploy platform-mesh, semver: {{ .COMPONENT_PRERELEASE_VERSION }}"
-        yq -i '.spec.semver = "{{ .COMPONENT_PRERELEASE_VERSION }}"' local-setup/kustomize/overlays/ocm-prerelease/prerelease-component.yml
-
-      - | # apply kustomize patch only for configured charts in CUSTOM_LOCAL_COMPONENTS_CHART_PATHS
-        patch_string=""
-        for pair in {{ range .CUSTOM_LOCAL_COMPONENTS_CHART_PATHS }}"{{ range $k,$v := . }}{{$k}}:{{$v}}{{ end }}" {{ end }}; do
-          comp="${pair%%:*}"
-          patch_string+=$(cat <<EOF
-        - op: add
-          path: /spec/values/$comp
-          value: {}
-        - op: add
-          path: /spec/values/$comp/ocm
-          value: {}
-        - op: add
-          path: /spec/values/$comp/ocm/repo
-          value: {}
-        - op: add
-          path: /spec/values/$comp/ocm/repo/name
-          value: prerelease
-        - op: add
-          path: /spec/values/$comp/ocm/component
-          value: {}
-        - op: add
-          path: /spec/values/$comp/ocm/component/name
-          value: prerelease
-        EOF
-          )
-          patch_string+=$'\n'
-        done
-
-        # Use yq to update the kustomization.yaml file
-        yq -i '.patches[0].patch = "'"$patch_string"'"' local-setup/kustomize/overlays/ocm-prerelease/kustomization.yaml
+        yq -i '.spec.semver = "{{ .COMPONENT_PRERELEASE_VERSION }}"' local-setup/kustomize/components/ocm-component/component.yaml
 
       - |
-        kubectl apply -k local-setup/kustomize/overlays/ocm-prerelease
+        kubectl apply -k local-setup/kustomize/overlays/default
         echo "Applied kustomize overlay"
       - kubectl rollout restart deployment/ocm-k8s-toolkit-controller-manager -n ocm-system
 
@@ -525,3 +505,25 @@ tasks:
           npx playwright install
           npx playwright test test-minimal.test.ts
           popd
+
+  local-setup-with-ocm:iterate:
+    deps:
+      - task: setup:mkcert
+    env:
+      START_MID_HOOK: "task ocm:deploy ocm:build ocm:apply"
+      START_MID_HOOK2: "task patch-platformmesh-hostaliases"
+    cmds:
+      - |
+        # read -r -p "Are you sure you want to delete the cluster? [y/N] " response && if [ "$response" != "y" ]; then echo "Aborted."; exit 1; fi
+        # kind delete cluster --name platform-mesh
+        START_MID_HOOK=$START_MID_HOOK START_MID_HOOK2=$START_MID_HOOK2 ./local-setup/scripts/start.sh
+        # ./local-setup/scripts/start.sh
+
+
+  patch-platformmesh-hostaliases:
+    cmds:
+      - |
+        HOST_IP=$(kubectl get svc traefik -o json | jq -r '.spec.clusterIP') \
+        yq -i '(.patches[] | select(has("patch")).patch) |= (from_yaml | with(.[]; .value = env(HOST_IP)) | to_yaml)' local-setup/kustomize/overlays/hostAliases/kustomization.yaml
+        kubectl apply -k local-setup/kustomize/overlays/hostAliases
+        kubectl rollout restart deployment/platform-mesh-operator -n platform-mesh-system
