refactor(scripts): - restore start.sh and related tasks - move remote deployment to start-remotedeployment.sh
On-behalf-of: @SAP angel.kafazov@sap.com
Signed-off-by: Angel Kafazov <akafazov@cst-bg.net>

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -581,3 +581,20 @@ tasks:
     cmds:
       - task: local-setup:iterate
         vars: {FLAGS: "--cached --latest --example-data"}
+
+  local-setup-remotedeployment:
+    deps:
+      - task: setup:mkcert
+    vars:
+      FLAGS: '{{.FLAGS | default ""}}'
+    cmds:
+      - |
+        if kind get clusters 2>/dev/null | grep -q "^platform-mesh$"; then
+          read -r -p "Are you sure you want to delete the runtime cluster? [y/N] " response && if [ "$response" != "y" ]; then echo "Aborted."; exit 1; fi
+          kind delete cluster --name platform-mesh
+        fi
+        if kind get clusters 2>/dev/null | grep -q "^platform-mesh-infra$"; then
+          read -r -p "Are you sure you want to delete the infra cluster? [y/N] " response && if [ "$response" != "y" ]; then echo "Aborted."; exit 1; fi
+          kind delete cluster --name platform-mesh-infra
+        fi
+        local-setup/scripts/start-remotedeployment.sh {{.FLAGS}}
